[workspace]
name = "Swedish Earth Biogenome Project Assembly Pipeline"
version = "0.1.0"
description = "A de novo genome assembly pipeline"
authors = [
    "Mahesh Binzer-Panchal <mahesh.binzer-panchal@nbis.se>",
    "Cormac Kinsella <cormac.kinsella@nbis.se>",
    "Martin Pippel <martin.pippel@nbis.se>",
    "André Soares <andre.soares@nbis.se>",
    "Guilherme Dias <guilherme.dias@nbis.se>",
    "Lucile Soler <lucile.soler@nbis.se>"
]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64", "osx-64", "osx-arm64"]

[tasks]
# Run Nextflow directly
test-docker = "nextflow run main.nf -profile docker,test"
test-singularity = "nextflow run main.nf -profile singularity,test"
dev = { cmd = "nextflow run main.nf -profile docker,test,debug --oatkdb database_cache/OatkDB/v20230921", depends-on = [ "fetch-oatkdb" ] }
# Run nf-tests
nftest-docker = "nf-test test tests/main.nf.test --verbose"
nftest-singularity = "nf-test test tests/main.nf.test --verbose --profile singularity"
# Clean up
clean-work = "nextflow clean -f -before last && find work/ -type d -empty -delete"
clean-all = "git clean -e .pixi -e .vscode -e database_cache -fdx"
# Stage data dependencies
fetch-oatkdb = { cmd = "mkdir -p database_cache && cd database_cache && git clone --depth 1 https://github.com/c-zhou/OatkDB.git", outputs = [ "database_cache/OatkDB" ] }

[dependencies]
nextflow = ">=26.4.1,<27"
nf-core = ">=4.0.2,<5"
nf-test = ">=0.9.5,<0.10"
