channels:
- conda-forge
- bioconda
dependencies:
- bioconda::multiqc=1.25
- conda-forge::jupyter=1.1.1
- conda-forge::pandas=2.2.3
- conda-forge::papermill=2.6.0
- conda-forge::quarto=1.5.57
- conda-forge::tabulate=0.9.0