title: "BGE Assembly Report"
output_fn_name: BGE_assembly_multiqc_report.html
intro_text: |
  An assembly report for the BGE project.

ignore_images: false
disable_version_detection: true

module_order:
  - "dtol"
  - "traits"
  # - "Custom insert curation notes", e.g. like methodology section
  - "Data Profile"
  - "genescope"
  - "katgc"
  - "ploidyplot"
  - "busco"
  - "quast"
  - "Software versions - Assembly"
  - "Software versions - Curation"
  - "Assembly metrics"
  - "Contact Maps"
  - "Merqury"
  - "Blobtools"

custom_data:
  dtol:
    file_format: "tsv"
    section_name: "DToL"
    description: "Darwin Tree of Life identifier and related meta data."
    plot_type: "table"
  traits:
    file_format: "tsv"
    section_name: "Genome traits"
    description: "Sample genome traits."
    plot_type: "table"
  genescope:
    section_name: "GenomeScope2"
    description: "Sample data k-mer histogram."
  ploidyplot:
    file_format: "png"
    section_name: "Ploidy Plot"
    description: "Ploidy estimate based on kmers."
  katgc:
    file_format: "png"
    section_name: "GC Content"
    description: "Sequence GC content."

sp: # Search pattern
  dtol:
    fn: "DToL.tsv"
  traits:
    fn: "Genome_traits.tsv"
  ploidyplot:
    fn: "*_ploidyplot.st.png"
  katgc:
    fn: "*_katgc.st.png"
